- name: Prez Stack Playbook
  hosts: webservers
  vars_files:
    - group_vars/container_image.yml
    - group_vars/fuseki.yml
    - group_vars/letsencrypt.yml
    - group_vars/nginx.yml
    - group_vars/prez_ui.yml
    - group_vars/swapfile.yml
    - group_vars/vault.yml

  remote_user: "{{ vault.server.user }}"

  roles:
    - name: nginx.install
      tags:
        - nginx.install

    - name: podman.install
      tags:
        - podman.install

    - name: swapfile.enable
      tags:
        - swapfile.enable

    - name: fuseki.install
      tags:
        - fuseki.install

    - name: fuseki.data.setup
      tags:
        - fuseki.data.setup

    - name: fuseki.data.create
      tags:
        - fuseki.data.create

    - name: fuseki.data.configure
      tags:
        - fuseki.data.configure
